### ISSUE TITLE
Menu screens / black background

### ISSUE THREAD

**Issue by jmbau** [SearchAndRescue2/sar2#10]
Hello,
I experienced some graphical issues on menu screens. Sometimes, the background becomes black and some buttons / sliders disappears. When I move randomly the mouse cursor on the Sar2 window, sometime only some buttons / sliders reappears, and sometimes background and all buttons / sliders reappears. I don't have this problem on simulation / simulation map screens.
I use Linux.
![black_background](https://user-images.githubusercontent.com/30726620/28973224-f227bdf2-7932-11e7-8dd2-0d3a3aece946.png)

BR

**Comment by hsanjuan** [comment]
I have this too and I have no idea why it happens yet...

**Comment by hsanjuan** [comment]
I think this is not as bad as before, but it still happens someones on fullscreen when hovering on some element/button (at least for me, not sure if this is the only combination).

**Comment by jmbau** [comment]
Hello Hector,
I have still the problem too, even in a window (not fullscreen). Hereunder is how I can reproduce the glitch, at least on my computer :
1) go to option page
2)  move vertically (hover) the mouse cursor on the buttons
=> all, except the luminous buttons, disappears and reappears randomly.
I see that:
a) If I move the mouse quickly, more than one button can light at a time
b) If I activate an other application window, then go back to the Sar2 window, the glitch totally disappears, as long as I stay on this menu !. Even if Sar2 window was black when I activate the other application window then reactivate Sar2 window, it becomes "non-black".
c) If I go back to main menu page, then go to option page, the glitch reappears. If I redo step b), the glitch disappears.
Hope this will help.

**Comment by hsanjuan** [comment]
To me it happens after switching fro fullscreen to windowed, and keeps happening back to full screen :S

Actually there is a startup option `--full_menu_redraw` that seems to fix this. I am going to enable it by default.
