### ISSUE TITLE
SAR2 available on ArchLinux via AUR package

### ISSUE THREAD

**Issue by Popolon** [SearchAndRescue2/sar2#18]
I just created today an AUR package for ArchLinux :

https://aur.archlinux.org/packages/sar2/

yay -S sar2 # could complain about missing scons. Need to install it manually (sudo pacman -S scons)
pacman -S sar2 # ask automatically to user if he want to install scons

**Comment by hsanjuan** [comment]
Thank you very much! I have added a mention to the README and to the Downloads page in the website (https://searchandrescue2.github.io/sar2/#download).
