### ISSUE TITLE
Remove Sourceforge references

### ISSUE THREAD

**Issue by hsanjuan** [SearchAndRescue2/sar2#2]
Since sar2 was moved to github I forgot to remove some references in Readme's etc. Now that sar2 has been removed from sourceforge, they are broken. #1 reminded me of this.

**Comment by ZeZiNhOo** [comment]
No way to download it?

**Comment by hsanjuan** [comment]
To download the game?

You can either clone the repo or download https://github.com/hsanjuan/sar2/archive/master.zip

You would need to compile it though (unless you grab some of the existing packages for some distro). Installation instructions are here: https://github.com/hsanjuan/sar2/blob/master/INSTALL

**Comment by ZeZiNhOo** [comment]
Sorry, I meant that the site still indicate sourceforge as download page, and it does not exist anymore.
For git, while I know how to use it, may I suggest to make releases, which are much easier to follow by distros (I package for Mageia Linux).

**Comment by zezinho42** [comment]
Fedora package is version 2.3.0, while I can see 2.3.1 in changelog. Was this 2.3.1 version released?

**Comment by hsanjuan** [comment]
@zezinho42 Yes I think so

**Comment by zezinho42** [comment]
I'd like to help a little this project if you do not have time : make true releases, update web page that links to SF... or do you have time to do so?

**Comment by hsanjuan** [comment]
@zezinho42 that's great! I don't have real time for it. If you'd like, I can create and move this repository into a Github organization and  then give you admin rights. It's a very beautiful game after all.

**Comment by zezinho42** [comment]
Le 19/12/2016 à 22:48, Hector Sanjuan a écrit :
> @zezinho42 <https://github.com/zezinho42> that's great! I don't have
> real time for it. If you'd like, I can create and move this repository
> into a Github organization and then give you admin rights. It's a very
> beautiful game after all.
>

Ok. I have never done that, it's time to learn!

**Comment by hsanjuan** [comment]
ok it's now moved and I have invited you

**Comment by zezinho42** [comment]
I have tried to prepare a release, but it seems you did not gave me admin :



remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least one approved review is required
To https://github.com/SearchAndRescue2/sar2.git
  ! [remote rejected] master -> master (protected branch hook declined)

**Comment by hsanjuan** [comment]
Hi @zezinho42, master branch is protected on purpose and no one can push directly to it. Please create a different branch, push to it, and then make a pull request so I can review the changes and hopefully be able to provide feedback if needed.

Here is a guide of this sort of flow: https://guides.github.com/introduction/flow/

I hope you understand I need to keep an eye on changes for the moment.

**Comment by zezinho42** [comment]
Le 22/12/2016 à 10:16, Hector Sanjuan a écrit :
> I hope you understand I need to keep an eye on changes for the moment.

Of course. Pull request done.
