### ISSUE TITLE
Objective can be completed with only half of humans to hoist

### ISSUE THREAD

**Issue by jmbau** [SearchAndRescue2/sar2#20]
Hello,

objective->humans_need_rescue is decremented twice when a hoisted human enters aircraft.

Here is the result:
When number of humans to rescue is an even number, hoisting half of humans to rescue is enough to complete objective.
When number of humans to rescue is an odd number, hoisting half of humans to rescue plus one humans is enough to complete objective.

I made some test:
- the first decrementation is in mission.c / SARMissionPassengersEnterNotify() function, line #906 (objective->humans_need_rescue -= passengers_entered;)
- the second one is in mission.c / SARMissionHoistInNotify() function, line #810 (objective->humans_need_rescue -= hoisted_in;). This decrementation occurs only when objective->humans_need_rescue is greater than 0.

I don't have enough programming knowledge to go further...

**Comment by hsanjuan** [comment]
So one decrement is related to humans entering the aircraft, and the other with humans being hoisted-in. Do you think both are called for the same human?

Given the human objects are deleted when doing that I would expect that they cannot  be counted twice.

**Comment by jmbau** [comment]
I don't know if both are called for the same human. I just made a test with **Training 6: Medium Endurance** mission : there are 3 humans to hoist, but when the second one is aboard, the first _mission_objective_message_success_ appears, and if you land at hospital without the third mock victim, the second _mission_objective_message_success_ appears and mission is considered as accomplished. I think that the 3rd guy is not very happy about that ;-)
