### ISSUE TITLE
unable to load sar2.xpm

### ISSUE THREAD

**Issue by beew** [SearchAndRescue2/sar2#22]
Hi, 

I built sar2 from source and installed it in the prefix= $HOME/sar2

 I then exported SAR2_DATA=$HOME/sar2/share/sar2

But when running the binary, it complains that 
/usr/share/pixmaps/sar2.xpm: Unable to load

sar2 is in $HOME/sar2/share/pixmaps

What environmental variable do I need to specify the pixmaps directory?

Also how to specify the manual directory?

OS is Ubuntu 20.04,

**Comment by hsanjuan** [comment]
Hi,

that path is hardcoded. The error can be fully ignored though. You can put the sar2.xpm icon on that path, or, since you are building from source, you can edit `src/config.h` and point it to the right place.

As said, it does not matter much.
