### ISSUE TITLE
V22-Osprey: both rotors are CCW, when only one should be

### ISSUE THREAD

**Issue by hsanjuan** [SearchAndRescue2/sar2#48]
Both rotors in this "copter" are rotating in the same direction.

However in reality (https://www.youtube.com/watch?v=MNEIgklBTSg), they rotate in opposite directions (thus compensating the many of the single-rotor aerodynamics).

The Kamov KA-27 does have two rotors and they do rotate in different directions as in the real world.

**Comment by hsanjuan** [comment]
So pitching the rotor 180 as done in the KA-27 model does not work because then breaks on tilting I think (perhaps just banking 180 does it). However when this is done the blades are at negative angles.

**Comment by jmbau** [comment]
You're right, banking rotor is not enough: left rotor blades 3d model must be symmetric and blades blur position must be inverted.
I made a patch:

patch -p0 < ./V22_issue_48.txt
[V22_issue_48.txt](https://github.com/SearchAndRescue2/sar2/files/12717402/V22_issue_48.txt)
